apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -o ./k8s
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: metastore
  name: metastore
spec:
  ports:
    - name: "9083"
      port: 9083
      targetPort: 9083
  selector:
    io.kompose.service: metastore
status:
  loadBalancer: {}
