apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: s3demo1
spec:
  mounts:
    - mountPoint: s3a://spark-bucket/warehouse
      name: spark
      options:
        alluxio.underfs.s3.endpoint: http://minio:9000
        alluxio.underfs.s3.disable.dns.buckets: "true"
        alluxio.underfs.s3.inherit.acl: "false"
      encryptOptions:
      - name: aws.accessKeyId
        valueFrom:
          secretKeyRef:
            name: s3secret
            key: s3.accessKeyId
      - name: aws.secretKey
        valueFrom:
          secretKeyRef:
            name: s3secret
            key: s3.secretKey
--- 
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  name: s3demo1
spec:
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 500M
        high: "0.95"
        low: "0.7"            